### ISSUE TITLE
Bug: Cannot generate coverage report with LuaCov

### ISSUE THREAD

**Issue by linrongbin16** [notomo/vusted#22]
Hi, I found with latest vusted version 2.5.0-1, the `--coverage` option cannot generate coverage report file.

Install steps:

```bash
luarocks install luacov
luarocks install luacov-reporter-lcov
luarocks --lua-version=5.1 install vusted
vusted --coverage ./spec
```

The [LuaCov](https://github.com/lunarmodules/luacov) can integrate with busted with the `--coverage` options, see busted docs [Usage - busted](https://lunarmodules.github.io/busted/). It should generate the coverage report file `luacov.stats.out`.

But with latest version, there is no such file, would you please take a look?

**Comment by notomo** [comment]
Thanks!

5f30cee broke coverage option.
v2.5.1 fixed this!

**Comment by linrongbin16** [comment]
@notomo , thank you for fixing it so fast!!!
