### ISSUE TITLE
Run test case/suite in clean environment

### ISSUE THREAD

**Issue by weilbith** [notomo/vusted#4]
Hey, 👋🏻 
thank you for this cool project! It looks really promising. I can't wait to try it out very soon. The documentation is quite limited but I just skimmed through all source files. 

One thing I'm missing is how I can ensure that each test case or suite runs in a clean NeoVim environment.
I tried to find out how other projects (partially using `vusted`) do this. It kinda looks like they use a before hook to reset as much as possible. Doing this correctly seems like a ton of work. There are so many things to keep care of (I don't even dare to start a listing here). So I guess it would make sense to provide such an overall reset function for everyone or even inject this globally into busted.
A more invasive but also very complete solution would be to run each test case or suite in its own NeoVim instance. I actually think this is how `plenary.nvim` does it. But I like `vusted` it's approach more... 

I would love to discuss this topic and maybe contribute with a PR. Looking forward to get feedback.

**Comment by notomo** [comment]
Thanks!

I think this function is need.

> So I guess it would make sense to provide such an overall reset function for everyone or even inject this globally into busted.

That makes sense.
I would like to provide this as `vusted.helper` function.
I think that simple unit tests without vim state should avoid doing too many cleanup.
So user should call the cleanup function explicitly.

**Comment by dhruvmanila** [comment]
The `--clean` flag is worth looking into. According to `man nvim`:
```
     --clean     Mimic a fresh install of Nvim. Skip loading non-builtin plugins and shada (viminfo) file.
```

Opening Neovim using the current `VUSTED_ARGS` adds the third-party plugin directory and config directory to the runtime path, while for `--clean` flag it does not.
1. `nvim -u NONE -i NONE -n` / `nvim --clean`
2. `:echo &runtimepath`

Also, I don't know which version was the flag added, so we might have to look into that as well.

**Comment by notomo** [comment]
> The --clean flag is worth looking into.

Thanks!
Though this seems to be related another problem, that sounds good.
